base/urls.py
from django.conf.urls import url
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('country/list/', views.CountryList.as_view(), name='country_list'),
    path('country/create/', views.CountryCreate.as_view(), name='country_create'),
    path('country/update/<int:pk>', views.CountryUpdate.as_view(), name='country_update'),
    path('country/delete/<int:pk>', views.CountryDelete.as_view(), name='country_delete'),

    path('district/list/', views.DistrictList.as_view(), name='district_list'),
    path('district/create/', views.DistrictCreate.as_view(), name='district_create'),
    path('district/update/<int:pk>', views.DistrictUpdate.as_view(), name='district_update'),
    path('district/delete/<int:pk>', views.DistrictDelete.as_view(), name='district_delete'),

    path('region/list/', views.RegionList.as_view(), name='region_list'),
    path('region/create/', views.RegionCreate.as_view(), name='region_create'),
    path('region/update/<int:pk>', views.RegionUpdate.as_view(), name='region_update'),
    path('region/delete/<int:pk>', views.RegionDelete.as_view(), name='region_delete'),

    path('sector/list/', views.SectorList.as_view(), name='sector_list'),
    path('sector/create/', views.SectorCreate.as_view(), name='sector_create'),
    path('sector/update/<int:pk>', views.SectorUpdate.as_view(), name='sector_update'),
    path('sector/delete/<int:pk>', views.SectorDelete.as_view(), name='sector_delete'),

]

operations/urls.py
from django.urls import path
from django.conf.urls import url

from operations import views

app_name = 'operations'

urlpatterns = [
    path('costcenter/list/', views.CostCenterList.as_view(), name='costcenter_list'),
    path('costcenter/create/', views.CostCenterCreate.as_view(), name='costcenter_create'),
    path('costcenter/update/<int:pk>', views.CostCenterUpdate.as_view(), name='costcenter_update'),
    path('costcenter/delete/<int:pk>', views.CostCenterDelete.as_view(), name='costcenter_delete'),

    path('repayment/list/', views.RepaymentList.as_view(), name='repayment_list'),
    path('repayment/create/', views.RepaymentCreate.as_view(), name='repayment_create'),
    path('repayment/update/<int:pk>', views.RepaymentUpdate.as_view(), name='repayment_update'),
    path('repayment/delete/<int:pk>', views.RepaymentDelete.as_view(), name='repayment_delete'),

    path('expensecategory/list/', views.ExpenseCategoryList.as_view(), name='expensecategory_list'),
    path('expensecategory/create/', views.ExpenseCategoryCreate.as_view(), name='expensecategory_create'),
    path('expensecategory/update/<int:pk>', views.ExpenseCategoryUpdate.as_view(), name='expensecategory_update'),
    path('expensecategory/delete/<int:pk>', views.ExpenseCategoryDelete.as_view(), name='expensecategory_delete'),

    path('incomecategory/list/', views.IncomeCategoryList.as_view(), name='incomecategory_list'),
    path('incomecategory/create/', views.IncomeCategoryCreate.as_view(), name='incomecategory_create'),
    path('incomecategory/update/<int:pk>', views.IncomeCategoryUpdate.as_view(), name='incomecategory_update'),
    path('incomecategory/delete/<int:pk>', views.IncomeCategoryDelete.as_view(), name='incomecategory_delete'),

    url(r'^expense/list/$', views.ExpenseList.as_view(), name='expense_list'),
    url(r'^income/list/$', views.IncomeList.as_view(), name='income_list'),
]

proact/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projects.models import CustomObtainToken
from base.views import index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^base/', include('base.urls', namespace='base')),

    url(r'^api/token-auth/', CustomObtainToken.as_view()),

    url(r'^api/base/', include('base.api_urls', namespace='api_base')),
    url(r'^api/projects/', include('projects.api_urls', namespace='api_projects')),
    url(r'^api/operations/', include('operations.api_urls', namespace='api_operations')),
]

operations/models.py
from django.db import models

from projects.models import Project, Staff, Employee


class Repayment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField()
    loan_amount = models.FloatField()
    paid_amount = models.FloatField()


class CostCenter(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)


class ExpenseCategory(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)


class Expenses(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    amount = models.FloatField()
    cost_center = models.ForeignKey(CostCenter, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    expense_category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)


class IncomeCategory(models.Model):
    name = models.CharField(max_length=255)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Income(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    amount = models.FloatField()
    cost_center = models.ForeignKey(CostCenter, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    income_category = models.ForeignKey(IncomeCategory, on_delete=models.CASCADE)

operations/views.py
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from projects.models import Staff

from operations.models import (
    Repayment,
    CostCenter,
    Expenses,
    ExpenseCategory,
    Income,
    IncomeCategory
)



class RepaymentList(ListView):
    model = Repayment


class RepaymentCreate(CreateView):
    model = Repayment
    fields = '__all__'
    success_url = reverse_lazy('operations:repayment_list')


class RepaymentDelete(DeleteView):
    model = Repayment
    success_url = reverse_lazy('operations:repayment_list')


class RepaymentUpdate(UpdateView):
    model = Repayment
    fields = '__all__'
    success_url = reverse_lazy('operations:repayment_list')

    
class CostCenterList(ListView):
    model = CostCenter


class CostCenterCreate(CreateView):
    model =CostCenter
    fields = '__all__'
    success_url = reverse_lazy('operations:costcenter_list')


class CostCenterDelete(DeleteView):
    model = CostCenter
    success_url = reverse_lazy('operations:costcenter_list')


class CostCenterUpdate(UpdateView):
    model = CostCenter
    fields = '__all__'
    success_url = reverse_lazy('operations:costcenter_list')


class ExpenseList(ListView):
    model = Expenses


class ExpenseCategoryList(ListView):
    model = ExpenseCategory


class ExpenseCategoryCreate(CreateView):
    model = ExpenseCategory
    fields = '__all__'
    success_url = reverse_lazy('operations:expensecategory_list')


class ExpenseCategoryDelete(DeleteView):
    model = ExpenseCategory
    success_url = reverse_lazy('operations:expensecategory_list')


class ExpenseCategoryUpdate(UpdateView):
    model = ExpenseCategory
    fields = '__all__'
    success_url = reverse_lazy('operations:expensecategory_list')


class IncomeList(ListView):
    model = Income


class IncomeCategoryList(ListView):
    model = IncomeCategory


class IncomeCategoryCreate(CreateView):
    model = IncomeCategory
    fields = '__all__'
    success_url = reverse_lazy('operations:incomecategory_list')


class IncomeCategoryDelete(DeleteView):
    model = IncomeCategory
    success_url = reverse_lazy('operations:incomecategory_list')


class IncomeCategoryUpdate(UpdateView):
    model = IncomeCategory
    fields = '__all__'
    success_url = reverse_lazy('operations:incomecategory_list')

operations/templates/operations/costcenter_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

operations/templates/operations/costcenter_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Cost center</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

operations/templates/operations/costcenter_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Sector list</h4>
            </td>
            <td><a href="{% url 'operations:costcenter_create' %}" class="btn btn-primary float-right">New cost center</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for cost_center in object_list %}
        <tr>
            <td>{{ cost_center.name }}</td>
            <td>
                <a href="{% url 'operations:costcenter_update' pk=cost_center.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'operations:costcenter_delete' pk=cost_center.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

operations/templates/operations/expensecategory_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

operations/templates/operations/expensecategory_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Expense category</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

operations/templates/operations/expensecategory_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Expense category list</h4>
            </td>
            <td><a href="{% url 'operations:expensecategory_create' %}" class="btn btn-primary float-right">New expense category</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for expensecategory in object_list %}
        <tr>
            <td>{{ expensecategory.name }}</td>
            <td>
                <a href="{% url 'operations:expensecategory_update' pk=expensecategory.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'operations:expensecategory_delete' pk=expensecategory.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

operations/templates/operations/incomecategory_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

operations/templates/operations/incomecategory_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Income category</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

operations/templates/operations/incomecategory_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Income category list</h4>
            </td>
            <td><a href="{% url 'operations:incomecategory_create' %}" class="btn btn-primary float-right">New income category</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for incomecategory in object_list %}
        <tr>
            <td>{{ incomecategory.name }}</td>
            <td>
                <a href="{% url 'operations:incomecategory_update' pk=incomecategory.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'operations:incomecategory_delete' pk=incomecategory.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

operations/templates/operations/repayment_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

operations/templates/operations/repayment_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Repayment</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

operations/templates/operations/repayment_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Repayment list</h4>
            </td>
            <td><a href="{% url 'operations:repayment_create' %}" class="btn btn-primary float-right">New repayment</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Loan amount</th>
        <th>Paid amount</th>
        <th>Date</th>

        {% for repayment in object_list %}
        <tr>
            <td>{{ repayment.project.name }}</td>
            <td>{{ repayment.loan_amount}}</td>
            <td>{{ repayment.paid_amount}}</td>
            <td>{{ repayment.date}}</td>
            <td>
                <a href="{% url 'operations:repayment_update' pk=repayment.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'operations:repayment_delete' pk=repayment.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}