base/urls.py
from django.conf.urls import url
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('country/list/', views.CountryList.as_view(), name='country_list'),
    path('country/create/', views.CountryCreate.as_view(), name='country_create'),
    path('country/update/<int:pk>', views.CountryUpdate.as_view(), name='country_update'),
    path('country/delete/<int:pk>', views.CountryDelete.as_view(), name='country_delete'),

    path('district/list/', views.DistrictList.as_view(), name='district_list'),
    path('district/create/', views.DistrictCreate.as_view(), name='district_create'),
    path('district/update/<int:pk>', views.DistrictUpdate.as_view(), name='district_update'),
    path('district/delete/<int:pk>', views.DistrictDelete.as_view(), name='district_delete'),

    path('region/list/', views.RegionList.as_view(), name='region_list'),
    path('region/create/', views.RegionCreate.as_view(), name='region_create'),
    path('region/update/<int:pk>', views.RegionUpdate.as_view(), name='region_update'),
    path('region/delete/<int:pk>', views.RegionDelete.as_view(), name='region_delete'),

    path('sector/list/', views.SectorList.as_view(), name='sector_list'),
    path('sector/create/', views.SectorCreate.as_view(), name='sector_create'),
    path('sector/update/<int:pk>', views.SectorUpdate.as_view(), name='sector_update'),
    path('sector/delete/<int:pk>', views.SectorDelete.as_view(), name='sector_delete'),

]

proact/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projects.models import CustomObtainToken
from base.views import index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^base/', include('base.urls', namespace='base')),

    url(r'^api/token-auth/', CustomObtainToken.as_view()),

    url(r'^api/base/', include('base.api_urls', namespace='api_base')),
    url(r'^api/projects/', include('projects.api_urls', namespace='api_projects')),
    url(r'^api/operations/', include('operations.api_urls', namespace='api_operations')),
]

projects/urls.py
from django.conf.urls import url
from django.urls import path

from projects import views

app_name = 'projects'

urlpatterns = [
    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^project/list/$', views.ProjectList.as_view(), name='project_list'),
    path('project/details/<int:pk>/', views.project_details, name='project_details'),

    path('employeetype/create/', views.EmployeeTypeCreate.as_view(), name='employeetype_create'),
    path('employeetype/update/<int:pk>/', views.EmployeeTypeUpdate.as_view(), name='employeetype_update'),
    path('employeetype/delete/<int:pk>/', views.EmployeeTypeDelete.as_view(), name='employeetype_delete'),
    path('employeetype/list/', views.EmployeeTypeList.as_view(), name='employeetype_list'),
    path('employeetype/details/<int:pk>/', views.employeetype_details, name='employeetype_details'),

    path('employee/create/', views.EmployeeCreate.as_view(), name='employee_create'),
    path('employee/update/<int:pk>/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', views.EmployeeDelete.as_view(), name='employee_delete'),
    path('employee/list/', views.EmployeeList.as_view(), name='employee_list'),
    path('employee/details/<int:pk>/', views.employee_details, name='employee_details'),

    path('partner/create/', views.PartnerCreate.as_view(), name='partner_create'),
    path('partner/update/<int:pk>/', views.PartnerUpdate.as_view(), name='partner_update'),
    path('partner/delete/<int:pk>/', views.PartnerDelete.as_view(), name='partner_delete'),
    path('partner/list/', views.PartnerList.as_view(), name='partner_list'),
    path('partner/details/<int:pk>/', views.partner_details, name='partner_details'),
]

operations/models.py
from django.db import models

from projects.models import Project, Staff, Employee


class Repayment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField()
    loan_amount = models.FloatField()
    paid_amount = models.FloatField()


class CostCenter(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)


class ExpenseCategory(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)


class Expenses(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    amount = models.FloatField()
    cost_center = models.ForeignKey(CostCenter, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    expense_category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)


class IncomeCategory(models.Model):
    name = models.CharField(max_length=255)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Income(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    amount = models.FloatField()
    cost_center = models.ForeignKey(CostCenter, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    income_category = models.ForeignKey(IncomeCategory, on_delete=models.CASCADE)

projects/models.py
from django.contrib.auth.models import User
from django.db import models

from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response

from base.models import District, Sector


class CustomObtainToken(ObtainAuthToken):
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({'token': token.key, 'user': {'id': user.pk, 'name': user.get_full_name()},
                         'status': {'code':1, 'msg': 'Пользователь успешно залогинился'}})

FEMALE = 0
MALE = 1

GENDER = ((MALE, 'Мужской'), (FEMALE, 'Женский'))

class Partner(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Staff(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)


class EmployeeType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=200)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    partner_contribution = models.FloatField()
    own_contribution = models.FloatField()
    other_contribution = models.FloatField()
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    establish_year = models.SmallIntegerField()
    contact_phone = models.CharField(max_length=255, blank=True, null=True)
    contact_email = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Employee(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    gender = models.PositiveSmallIntegerField(choices=GENDER)
    employee_type = models.ForeignKey(EmployeeType, on_delete=models.CASCADE)
    start_date = models.DateField(auto_now=True)
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

projects/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Q

from projects.models import Project, EmployeeType, Employee, Partner


class ProjectCreate(CreateView):
    model = Project
    fields = '__all__'
    success_url = reverse_lazy('projects:project_list')


class ProjectList(ListView):
    model = Project
    

def project_details(request, pk):
    project = get_object_or_404(Project, pk=pk)
    ctx = {'project': project}
    return render(request, 'projects/project_details.html', ctx)


class EmployeeTypeCreate(CreateView):
    model = EmployeeType
    fields = '__all__'
    success_url = reverse_lazy('projects:employeetype_list')


class EmployeeTypeList(ListView):
    model = EmployeeType


def employeetype_details(request, pk):
    employee_type = get_object_or_404(EmployeeType, pk=pk)
    ctx = {'employee_type': employee_type}
    return render(request, 'projects/employeetype_details.html', ctx)


class EmployeeTypeDelete(DeleteView):
    model = EmployeeType
    success_url = reverse_lazy('projects:employeetype_list')


class EmployeeTypeUpdate(UpdateView):
    model = EmployeeType
    fields = '__all__'
    success_url = reverse_lazy('projects:employeetype_list')


class EmployeeCreate(CreateView):
    model = Employee
    fields = ('project', 'name', 'date_of_birth', 'gender', 'employee_type')
    success_url = reverse_lazy('projects:employee_list')


class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('projects:employee_list')



class EmployeeList(ListView):
    model = Employee


class EmployeeUpdate(UpdateView):
    model = Employee
    fields = ('project', 'name', 'date_of_birth', 'gender', 'employee_type')
    success_url = reverse_lazy('projects:employee_list')


def employee_details(request, pk):
    employee_type = get_object_or_404(Employee, pk=pk)
    ctx = {'employee': employee}
    return render(request, 'projects/employee_details.html', ctx)


class PartnerCreate(CreateView):
    model = Partner
    fields = '__all__'
    success_url = reverse_lazy('projects:partner_list')


class PartnerUpdate(UpdateView):
    model = Partner
    fields = '__all__'
    success_url = reverse_lazy('projects:partner_list')


class PartnerList(ListView):
    model = Partner


def partner_details(request, pk):
    partner = get_object_or_404(Partner, pk=pk)
    ctx = {'partner': partner}
    return render(request, 'projects/partner_details.html', ctx)


class PartnerDelete(DeleteView):
    model = Partner
    success_url = reverse_lazy('projects:partner_list')

projects/templates/projects/employee_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

projects/templates/projects/employee_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Create employee</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

projects/templates/projects/employee_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Employee list</h4>
            </td>
            <td>
                <a href="{% url 'projects:employee_create' %}" class="btn btn-primary float-right">New employee</a>
            </td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Full name</th>
        <th>Project</th>
        <th>Date of birth</th>
        <th>Gender</th>
        <th>Employee type</th>
        <th>Actions</th>

        {% for employee in object_list %}
        <tr>
            <td>{{ employee.name }}</td>
            <td>{{ employee.project}}</td>
            <td>{{ employee.date_of_birth }}</td>
            <td>{{ employee.get_gender_display }}</td>
            <td>{{ employee.employee_type }}</td>
            <td>
                <a href="{% url 'projects:employee_update' pk=employee.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'projects:employee_delete' pk=employee.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

projects/templates/projects/employeetype_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

projects/templates/projects/employeetype_details.html
{% extends 'base/index.html' %}

{% block body %}
    <h3>Employee type details</h3>
    <table class="table">
        <th>Name</th>
        <tr>
            <td>{{ employee_type.name }}</td>
        </tr>
    </table>

{% endblock %}

projects/templates/projects/employeetype_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Create employee type</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

projects/templates/projects/employeetype_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Employee type list</h4>
            </td>
            <td>
                <a href="{% url 'projects:employeetype_create' %}" class="btn btn-primary float-right">New employee type</a>
            </td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for employee_type in object_list %}
        <tr>
            <td>{{ employee_type.name }}</a></td>
            <td>
                <a href="{% url 'projects:employeetype_update' pk=employee_type.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'projects:employeetype_delete' pk=employee_type.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

projects/templates/projects/partner_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

projects/templates/projects/partner_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Update partner</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

projects/templates/projects/partner_list.html
{% extends 'base/index.html' %}

{% block body %}
<table width="100%">
    <tr>
        <td>
            <h4>Partner list</h4>
        </td>
        <td><a href="{% url 'projects:partner_create' %}" class="btn btn-primary float-right">New partner</a></td>
    </tr>
</table>
<br>
<table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for partner in object_list %}
        <tr>
            <td>{{ partner.name }}</td>
            <td>
                <a href="{% url 'projects:partner_update' pk=partner.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'projects:partner_delete' pk=partner.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

projects/templates/projects/project_details.html
{% extends 'base/index.html' %}

{% block body %}
    <h3>Project details</h3>
    <table class="table">
        <th>Name</th>
        <th>District</th>
        <th>Partner</th>
        <th>Owner</th>
        <th>Partner contribution</th>
        <th>Own contribution</th>
        <th>Other contribution</th>
        <th>Sector</th>
        <th>Establish year</th>
        <th>Contact phone</th>
        <th>Contact email</th>
        <tr>
            <td>{{ project.name }}</td>
            <td>{{ project.district }}</td>
            <td>{{ project.partner }}</td>
            <td>{{ project.owner }}</td>
            <td>{{ project.partner_contribution }}</td>
            <td>{{ project.own_contribution }}</td>
            <td>{{ project.other_contribution }}</td>
            <td>{{ project.sector }}</td>
            <td>{{ project.establish_year }}</td>
            <td>{{ project.contact_phone }}</td>
            <td>{{ project.contact_email }}</td>
        </tr>
    </table>


    <table width="100%">
        <th>Expenses</th>
        <th>&nbsp;</th>
        <th>Income</th>
        <tr>
            <td>
                <table class="table">
                    <th>Cost center</th>
                    <th>Expense category</th>
                    <th>Employee</th>
                    <th>Amount</th>
                    <th>Comment</th>
                    <th>Created at</th>

                    {% for expense in project.expenses_set.all %}
                        <tr>
                            <td>{{ expense.cost_center.name }}</td>
                            <td>{{ expense.expense_category.name }}</td>
                            <td>{{ expense.employee.get_full_name }}</td>
                            <td>{{ expense.amount }}</td>
                            <td>{{ expense.comment }}</td>
                            <td>{{ expense.created_at }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </td>

            <td></td>

            <td>
                <table class="table">
                    <th>Cost center</th>
                    <th>Expense category</th>
                    <th>Employee</th>
                    <th>Amount</th>
                    <th>Comment</th>
                    <th>Created at</th>

                    {% for expense in project.expenses_set.all %}
                        <tr>
                            <td>{{ expense.cost_center.name }}</td>
                            <td>{{ expense.expense_category.name }}</td>
                            <td>{{ expense.employee.get_full_name }}</td>
                            <td>{{ expense.amount }}</td>
                            <td>{{ expense.comment }}</td>
                            <td>{{ expense.created_at }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>

    </table>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Create project</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Project list</h4>
            </td>
            <td>
                <a href="{% url 'projects:project_create' %}" class="btn btn-primary float-right">New project</a>
            </td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>District</th>
        <th>Partner</th>
        <th>Owner</th>
        <th>Partner contribution</th>
        <th>Own contribution</th>
        <th>Other contribution</th>
        <th>Sector</th>
        <th>Establish year</th>
        <th>Contact phone</th>
        <th>Contact email</th>

        {% for project in object_list %}
        <tr>
            <td><a href="{% url 'projects:project_details' pk=project.pk %}">{{ project.name }}</a></td>
            <td>{{ project.district }}</td>
            <td>{{ project.partner }}</td>
            <td>{{ project.owner }}</td>
            <td>{{ project.partner_contribution }}</td>
            <td>{{ project.own_contribution }}</td>
            <td>{{ project.other_contribution }}</td>
            <td>{{ project.sector }}</td>
            <td>{{ project.establish_year }}</td>
            <td>{{ project.contact_phone }}</td>
            <td>{{ project.contact_email }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}