base/urls.py
from django.conf.urls import url
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('country/list/', views.CountryList.as_view(), name='country_list'),
    path('country/create/', views.CountryCreate.as_view(), name='country_create'),
    path('country/update/<int:pk>', views.CountryUpdate.as_view(), name='country_update'),
    path('country/delete/<int:pk>', views.CountryDelete.as_view(), name='country_delete'),

    path('district/list/', views.DistrictList.as_view(), name='district_list'),
    path('district/create/', views.DistrictCreate.as_view(), name='district_create'),
    path('district/update/<int:pk>', views.DistrictUpdate.as_view(), name='district_update'),
    path('district/delete/<int:pk>', views.DistrictDelete.as_view(), name='district_delete'),

    path('region/list/', views.RegionList.as_view(), name='region_list'),
    path('region/create/', views.RegionCreate.as_view(), name='region_create'),
    path('region/update/<int:pk>', views.RegionUpdate.as_view(), name='region_update'),
    path('region/delete/<int:pk>', views.RegionDelete.as_view(), name='region_delete'),

    path('sector/list/', views.SectorList.as_view(), name='sector_list'),
    path('sector/create/', views.SectorCreate.as_view(), name='sector_create'),
    path('sector/update/<int:pk>', views.SectorUpdate.as_view(), name='sector_update'),
    path('sector/delete/<int:pk>', views.SectorDelete.as_view(), name='sector_delete'),

]

operations/urls.py
from django.urls import path
from django.conf.urls import url

from operations import views

app_name = 'operations'

urlpatterns = [
    path('costcenter/list/', views.CostCenterList.as_view(), name='costcenter_list'),
    path('costcenter/create/', views.CostCenterCreate.as_view(), name='costcenter_create'),
    path('costcenter/update/<int:pk>', views.CostCenterUpdate.as_view(), name='costcenter_update'),
    path('costcenter/delete/<int:pk>', views.CostCenterDelete.as_view(), name='costcenter_delete'),

    path('repayment/list/', views.RepaymentList.as_view(), name='repayment_list'),
    path('repayment/create/', views.RepaymentCreate.as_view(), name='repayment_create'),
    path('repayment/update/<int:pk>', views.RepaymentUpdate.as_view(), name='repayment_update'),
    path('repayment/delete/<int:pk>', views.RepaymentDelete.as_view(), name='repayment_delete'),

    path('expensecategory/list/', views.ExpenseCategoryList.as_view(), name='expensecategory_list'),
    path('expensecategory/create/', views.ExpenseCategoryCreate.as_view(), name='expensecategory_create'),
    path('expensecategory/update/<int:pk>', views.ExpenseCategoryUpdate.as_view(), name='expensecategory_update'),
    path('expensecategory/delete/<int:pk>', views.ExpenseCategoryDelete.as_view(), name='expensecategory_delete'),

    path('incomecategory/list/', views.IncomeCategoryList.as_view(), name='incomecategory_list'),
    path('incomecategory/create/', views.IncomeCategoryCreate.as_view(), name='incomecategory_create'),
    path('incomecategory/update/<int:pk>', views.IncomeCategoryUpdate.as_view(), name='incomecategory_update'),
    path('incomecategory/delete/<int:pk>', views.IncomeCategoryDelete.as_view(), name='incomecategory_delete'),

    url(r'^expense/list/$', views.ExpenseList.as_view(), name='expense_list'),
    url(r'^income/list/$', views.IncomeList.as_view(), name='income_list'),
]

proact/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from projects.models import CustomObtainToken
from base.views import index


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^base/', include('base.urls', namespace='base')),

    url(r'^api/token-auth/', CustomObtainToken.as_view()),

    url(r'^api/base/', include('base.api_urls', namespace='api_base')),
    url(r'^api/projects/', include('projects.api_urls', namespace='api_projects')),
    url(r'^api/operations/', include('operations.api_urls', namespace='api_operations')),
]

projects/urls.py
from django.conf.urls import url
from django.urls import path

from projects import views

app_name = 'projects'

urlpatterns = [
    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^project/list/$', views.ProjectList.as_view(), name='project_list'),
    path('project/details/<int:pk>/', views.project_details, name='project_details'),

    path('employeetype/create/', views.EmployeeTypeCreate.as_view(), name='employeetype_create'),
    path('employeetype/update/<int:pk>/', views.EmployeeTypeUpdate.as_view(), name='employeetype_update'),
    path('employeetype/delete/<int:pk>/', views.EmployeeTypeDelete.as_view(), name='employeetype_delete'),
    path('employeetype/list/', views.EmployeeTypeList.as_view(), name='employeetype_list'),
    path('employeetype/details/<int:pk>/', views.employeetype_details, name='employeetype_details'),

    path('employee/create/', views.EmployeeCreate.as_view(), name='employee_create'),
    path('employee/update/<int:pk>/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', views.EmployeeDelete.as_view(), name='employee_delete'),
    path('employee/list/', views.EmployeeList.as_view(), name='employee_list'),
    path('employee/details/<int:pk>/', views.employee_details, name='employee_details'),

    path('partner/create/', views.PartnerCreate.as_view(), name='partner_create'),
    path('partner/update/<int:pk>/', views.PartnerUpdate.as_view(), name='partner_update'),
    path('partner/delete/<int:pk>/', views.PartnerDelete.as_view(), name='partner_delete'),
    path('partner/list/', views.PartnerList.as_view(), name='partner_list'),
    path('partner/details/<int:pk>/', views.partner_details, name='partner_details'),
]

base/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"

    def __str__(self):
        return self.name
    

class Region(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class District(models.Model):
    name = models.CharField(max_length=255, unique=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Sector(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    

base/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from base.models import Country, Region, District, Sector


def index(request):
    return render(request, 'base/index.html')


class CountryList(ListView):
    model = Country


class CountryCreate(CreateView):
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('base:country_list')


class CountryDelete(DeleteView):
    model = Country
    success_url = reverse_lazy('base:country_list')

class CountryUpdate(UpdateView):
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('base:country_list')


class DistrictCreate(CreateView):
    model = District
    fields = '__all__'
    success_url = reverse_lazy('base:district_list')


class DistrictDelete(DeleteView):
    model = District 
    success_url = reverse_lazy('base:district_list')

class DistrictUpdate(UpdateView):
    model = District
    fields = '__all__'
    success_url = reverse_lazy('base:district_list')


class DistrictList(ListView):
    model = District


class RegionList(ListView):
    model = Region


class RegionCreate(CreateView):
    model = Region
    fields = '__all__'
    success_url = reverse_lazy('base:region_list')


class RegionDelete(DeleteView):
    model = Region
    success_url = reverse_lazy('base:region_list')

class RegionUpdate(UpdateView):
    model = Region
    fields = '__all__'
    success_url = reverse_lazy('base:region_list')


class SectorList(ListView):
    model = Sector


class SectorCreate(CreateView):
    model = Sector
    fields = '__all__'
    success_url = reverse_lazy('base:sector_list')


class SectorDelete(DeleteView):
    model = Sector
    success_url = reverse_lazy('base:sector_list')

class SectorUpdate(UpdateView):
    model = Sector
    fields = '__all__'
    success_url = reverse_lazy('base:sector_list')

base/templates/base/country_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

base/templates/base/country_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Country</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

base/templates/base/country_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Country list</h4>
            </td>
            <td><a href="{% url 'base:country_create' %}" class="btn btn-primary float-right">New country</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for country in object_list %}
        <tr>
            <td>{{ country.name }}</td>
            <td>
                <a href="{% url 'base:country_update' pk=country.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'base:country_delete' pk=country.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

base/templates/base/district_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

base/templates/base/district_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>District</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

base/templates/base/district_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>District list</h4>
            </td>
            <td><a href="{% url 'base:district_create' %}" class="btn btn-primary float-right">New district</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for district in object_list %}
        <tr>
            <td>{{ district.name }}</td>
            <td>
                <a href="{% url 'base:district_update' pk=district.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'base:district_delete' pk=district.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

base/templates/base/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>accelerate prosperity</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <!-- Custom styles for this template -->
    <style>
      .starter-template {
        margin-top: 75px;
        margin-left: 10px;
        margin-right: 10px;
      }

      /* change the background color */
    .navbar{
        background-color: rgb(199, 255, 198) !important;
    }
    /* change the brand and text color */
    .navbar .navbar-brand,
    .navbar .navbar-text {
        color: rgba(24, 56, 212, 0.8) !important;
        padding: 0.8rem 1rem !important;
    }
    /* change the link color and add padding for height */
    .navbar .navbar-nav .nav-link {
        color: rgba(24, 56, 212, 0.8) !important;
        padding: 1rem 1rem !important;
    }
    /* change the color of active or hovered links */
    .navbar .nav-item.active .nav-link,
    .navbar .nav-item:hover .nav-link {
        color: rgba(24, 56, 212, 0.8) !important;
        background-color: rgb(32, 209, 29) !important; /* add background-color to active links */
    }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Accelerate prosperity</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Directories</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'projects:project_list' %}">Projects</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'operations:incomecategory_list' %}">Income categories</a>
              <a class="dropdown-item" href="{% url 'operations:expensecategory_list' %}">Expense categories</a>
              <a class="dropdown-item" href="{% url 'operations:repayment_list' %}">Repayment</a>
              <a class="dropdown-item" href="{% url 'operations:costcenter_list' %}">Cost centres</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'base:country_list' %}">Countries</a>
              <a class="dropdown-item" href="{% url 'base:district_list' %}">Districts</a>
              <a class="dropdown-item" href="{% url 'base:region_list' %}">Regions</a>
              <a class="dropdown-item" href="{% url 'base:sector_list' %}">Sectors</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'projects:employee_list' %}">Employees</a>
              <a class="dropdown-item" href="{% url 'projects:employeetype_list' %}">Employee types</a>
              <a class="dropdown-item" href="{% url 'projects:partner_list' %}">Partners</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reports</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
            </div>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>


    <main role="main" class="container-fluid">

      <div class="starter-template">
        <br>
        {% block body %} {% endblock %}
      </div>

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

base/templates/base/region_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

base/templates/base/region_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>District</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

base/templates/base/region_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Region list</h4>
            </td>
            <td><a href="{% url 'base:region_create' %}" class="btn btn-primary float-right">New region</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for region in object_list %}
        <tr>
            <td>{{ region.name }}</td>
            <td>
                <a href="{% url 'base:region_update' pk=region.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'base:region_delete' pk=region.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

base/templates/base/sector_confirm_delete.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
{% endblock %}

base/templates/base/sector_form.html
{% extends 'base/index.html' %}

{% block body %}
<form method="POST">
    <h3>Sector</h3>
    <table class="table">
        {% csrf_token %}
        {{form}}
        <tr>
            <td colspan="2"><input type="submit" class="btn btn-primary"></td>
        </tr>
    </table>
</form>
{% endblock %}

base/templates/base/sector_list.html
{% extends 'base/index.html' %}

{% block body %}
    <table width="100%">
        <tr>
            <td>
                <h4>Sector list</h4>
            </td>
            <td><a href="{% url 'base:sector_create' %}" class="btn btn-primary float-right">New sector</a></td>
        </tr>
    </table>
    <br>
    <table class="table">
        <th>Name</th>
        <th>Actions</th>

        {% for sector in object_list %}
        <tr>
            <td>{{ sector.name }}</td>
            <td>
                <a href="{% url 'base:sector_update' pk=sector.pk %}"><i class="fas fa-edit" style="color: blue"></i></a>
                <a href="{% url 'base:sector_delete' pk=sector.pk %}"><i class="fas fa-eraser" style="color: red"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}